import type { Metadata } from "next";
import { Montserrat, Kalam } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/Navbar";

const montSans = Montserrat({
  variable: "--font-mont-sans",
  subsets: ["latin"],
});

const kalam = Kalam({
  variable: "--font-kalam",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montSans.variable} ${kalam.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
